/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 5dba5da3dcd25c8bfe3c58e6c64d6fbd)
interface __BaseEnv_WorkerBindings {
	GUARD: DurableObjectNamespace<import("./src/index").Guard>;
	DESTINATION: DurableObjectNamespace<import("./src/index").Destination>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Guard" | "Destination";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
